name: Mend Demo

on: workflow_dispatch

          
jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: Download Mend CLI
      run: |
        echo Downloading Mend CLI
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
    - name: Mend CLI SCA Scan
      if: always()
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas-eu.mend.io
      run: |
        echo run Mend dependencies scan
        mend dep -u -r --export-results dep-results.txt
    - name: Mend CLI SCA Scan
      if: always()
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas-eu.mend.io
      run: |
        echo Run Mend code scan
        mend code -r --formats pdf --filename code-results --non-interactive
        cp code-results.sarif ~/.mend/logs
    - name: Create Mend Reports
      if: always()
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas-eu.mend.io
      run: |

        ### Generate Mend reports ###
          ### Obtain project token ###
          export WS_PROJECTTOKEN=$(grep -oP "(?<=token=)[^&]+" ~/.mend/logs/dep-results.txt)
          echo "FOUND TOKEN: $WS_PROJECTTOKEN"
          if [ -z "$WS_PROJECTTOKEN" ];
          then
            echo "No project token found, reports will not be generated"
          fi
          
            ### Run SBOM generator ###
            ### Requires admin priviledges ###
              echo "Generating SBOM report"
              pip install mend-sbom-export-cli
              sbom_export_cli --user-key ${MEND_USER_KEY} --service ${MEND_EMAIL} --url ${MEND_URL} --project ${WS_PROJECTTOKEN} --out ~/.mend/logs
            ### Dependency Reports (SCA) ###
            ### Risk Report
              echo "Generating Risk report"
              curl -o ~/.mend/logs/riskreport.pdf -X POST "${MEND_URL}/api/v1.4" -H "Content-Type: application/json" \
              -d '{"requestType":"getProjectRiskReport","userKey":"'${MEND_USER_KEY}'","projectToken":"'${WS_PROJECTTOKEN}'"}'
              echo "Generating Inventory report"
              curl -o ~/.mend/logs/inventoryreport.xlsx -X POST "${MEND_URL}/api/v1.4" -H "Content-Type: application/json" \
              -d '{"requestType":"getProjectInventoryReport","userKey":"'${MEND_USER_KEY}'","projectToken":"'${WS_PROJECTTOKEN}'"}'
              echo "Generating Due Diligence report"
              curl -o ~/.mend/logs/duediligencereport.xlsx -X POST "${MEND_URL}/api/v1.4" -H "Content-Type: application/json" \
              -d '{"requestType":"getProjectDueDiligenceReport","userKey":"'${MEND_USER_KEY}'","projectToken":"'${WS_PROJECTTOKEN}'"}'
    - name: Publish Mend Folder
      uses: actions/upload-artifact@v4
      with:
        name: "Mend CLI Logs"
        path: ~/.mend/logs
